version: '3.8'

services:
  hue-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HUE_BRIDGE_IP=${HUE_BRIDGE_IP}
      - HUE_USERNAME=${HUE_USERNAME}
      - HUE_AUTO_DISCOVER=true
    volumes:
      - ./:/var/www
      - /tmp/hue_cache:/tmp/hue_cache
    networks:
      - hue-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hue-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hue-api
    networks:
      - hue-network
    restart: unless-stopped

networks:
  hue-network:
    driver: bridge

volumes:
  redis_data: