version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "9000:9000"  # Xdebug
    environment:
      - HUE_BRIDGE_IP=${HUE_BRIDGE_IP}
      - HUE_USERNAME=${HUE_USERNAME}
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    volumes:
      - .:/workspace
      - /workspace/vendor
    networks:
      - hue-network
    working_dir: /workspace

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - hue-network

networks:
  hue-network:
    driver: bridge